In [1]:
import numpy as np

In [38]:
l = [1,5,8,13]

In [39]:
arr1d = np.array(l, dtype=np.int16)
arr1d

array([ 1,  5,  8, 13], dtype=int16)

In [ ]:
[ 1,  5,  8, 13] 
  0   1   2   3


In [6]:
arr1d[0]

1

In [7]:
arr1d[3]

13

In [8]:
arr1d[5]

IndexError: index 5 is out of bounds for axis 0 with size 4

In [9]:
arr1d

array([ 1,  5,  8, 13], dtype=int16)

In [10]:
print("Original Array", arr1d)

arr1d[1] = 12

print("Changed Array", arr1d)

Original Array [ 1  5  8 13]
Changed Array [ 1 12  8 13]


In [11]:
print("Original Array", arr1d)

arr1d[2] = 109

print("Changed Array", arr1d)

Original Array [ 1 12  8 13]
Changed Array [  1  12 109  13]


In [ ]:
print("Original Array", arr1d)

slice_array = arr1d[]

In [13]:
arr1d

array([  1,  12, 109,  13], dtype=int16)

In [16]:
arr1d[1:3]

array([ 12, 109], dtype=int16)

In [17]:
arr1d[0:3]

array([  1,  12, 109], dtype=int16)

In [18]:
arr1d[:3]

array([  1,  12, 109], dtype=int16)

In [19]:
arr1d[2:]

array([109,  13], dtype=int16)

In [20]:
arr1d

array([  1,  12, 109,  13], dtype=int16)

In [21]:
arr1d[-1]

13

In [22]:
arr1d[-4]

1

In [26]:
arr1d

array([  1,  12, 109,  13], dtype=int16)

In [27]:
arr1d[0:2]

array([ 1, 12], dtype=int16)

In [28]:
arr1d[0:2] = 55

In [29]:
arr1d

array([ 55,  55, 109,  13], dtype=int16)

In [30]:
arr1d[2:]

array([109,  13], dtype=int16)

In [45]:
l = [1,5,8,13]

arr1d = np.array(l, dtype=np.int16)
arr1d

array([ 1,  5,  8, 13], dtype=int16)

In [46]:
test_arr1 = arr1d
test_arr2 = arr1d.copy()

In [47]:
test_arr1

array([ 1,  5,  8, 13], dtype=int16)

In [48]:
test_arr2

array([ 1,  5,  8, 13], dtype=int16)

In [49]:
test_arr1[:2] = 85

print('Test array 1', test_arr1)
print('Original array', arr1d)

Test array 1 [85 85  8 13]
Original array [85 85  8 13]


In [52]:
test_arr2[:2] = 99

print('Test array 2', test_arr2)
print('Original array', arr1d)

Test array 2 [99 99  8 13]
Original array [85 85  8 13]
