In [2]:
import numpy as np

In [3]:
cities = np.array(['Syndey', 'Delhi', 'Mumbai', 'Boston', 'London'])
bool_data = np.array([True, False, True, True, False])


In [20]:
cities

array(['Syndey', 'Delhi', 'Mumbai', 'Boston', 'London'], dtype='<U6')

In [21]:
bool_data

array([ True, False,  True,  True, False])

In [22]:
cities[[ True, False,  True,  True, False]]

array(['Syndey', 'Mumbai', 'Boston'], dtype='<U6')

In [24]:
cities == 'Delhi'

array([False,  True, False, False, False])

In [ ]:
['Syndey', 'Delhi', 'Mumbai', 'Boston', 'London']

In [4]:
data = np.array([[1,2],[3,4], [5,6], [7,8], [9,10]])

data

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [26]:
bool_data

array([ True, False,  True,  True, False])

In [27]:
data[bool_data]

array([[1, 2],
       [5, 6],
       [7, 8]])

In [29]:
data[bool_data, 0]

array([1, 5, 7])

In [31]:
data[bool_data, :1]

array([[1],
       [5],
       [7]])

In [35]:
cities

array(['Syndey', 'Delhi', 'Mumbai', 'Boston', 'London'], dtype='<U6')

In [34]:
cities != 'Boston'

array([ True,  True,  True, False,  True])

In [36]:
~ (cities == 'Boston')

array([ True,  True,  True, False,  True])

In [37]:
data

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [38]:
data[~ (cities == 'Boston')]

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 9, 10]])

In [39]:
cond = ~ (cities == 'Boston')

data[cond]

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 9, 10]])

In [40]:
cities

array(['Syndey', 'Delhi', 'Mumbai', 'Boston', 'London'], dtype='<U6')

In [41]:
data

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [43]:
data[ (cities == 'Boston') | (cities == 'London')]

array([[7, 8]])

In [44]:
data[ (cities == 'Boston') & (cities == 'London')]

array([], shape=(0, 2), dtype=int32)

In [46]:
cities == 'Boston'

array([False, False, False,  True, False])

In [47]:
cities == 'London'

array([False, False, False, False,  True])

In [48]:
(cities == 'Boston') & (cities == 'London')

array([False, False, False, False, False])

In [60]:
cities

array(['Syndey', 'Delhi', 'Mumbai', 'Boston', 'London'], dtype='<U6')

In [61]:
arr = cities.copy()

arr[0] = 'Cairo'

In [62]:
arr

array(['Cairo', 'Delhi', 'Mumbai', 'Boston', 'London'], dtype='<U6')

In [63]:
cities

array(['Syndey', 'Delhi', 'Mumbai', 'Boston', 'London'], dtype='<U6')

In [65]:
new_var = data[ (cities == 'Boston')]

new_var

array([[7, 8]])

In [66]:
new_var[:]=5

In [67]:
new_var

array([[5, 5]])

In [68]:
data

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [69]:
new_var = data[:2]

new_var

array([[1, 2],
       [3, 4]])

In [70]:
new_var[:]=5

In [71]:
new_var

array([[5, 5],
       [5, 5]])

In [72]:
data

array([[ 5,  5],
       [ 5,  5],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [5]:
data

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [6]:
data < 5

array([[ True,  True],
       [ True,  True],
       [False, False],
       [False, False],
       [False, False]])

In [8]:
data[data >= 5]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
data < [2, 8]

array([[ True,  True],
       [False,  True],
       [False,  True],
       [False, False],
       [False, False]])

In [11]:
data

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])