In [1]:
import numpy as np

In [32]:
np.array([1,2,3,-129,-130], dtype=np.int8)

# -128 to +127

array([  1,   2,   3, 127, 126], dtype=int8)

In [105]:
np.array([1,2,3], dtype='u1')

array([1, 2, 3], dtype=uint8)

In [ ]:
-128 to 127

-129 -> 127
-130 -> 126


 -128 -127 -126 .. 0 .. 126 127 .. -128 .. 0 .. 126

In [31]:
np.array([1,2,3,-2,255], dtype=np.uint8)

# 0 to 255

array([  1,   2,   3, 254, 255], dtype=uint8)

In [ ]:
0 to 255

-1 -> 255
-2 -> 254


In [64]:
print(np.array([1,2,4,-500, -32768, 32767], dtype=np.int16))

# -32768  to - 32767

start = - (2**16) // 2 

end = (2**16) // 2 - 1

start, end

[     1      2      4   -500 -32768  32767]


(-32768, 32767)

In [65]:
print(np.array([1,2,4,-500, 500, 0, 65536], dtype=np.uint16))

# 0 to 65536
# 2 ** 16

start = 0
end = 2**16

start, end

[    1     2     4 65036   500     0     0]


(0, 65536)

In [76]:
np.array([1,5,8,7, 2147483647], dtype=np.int32)

array([         1,          5,          8,          7, 2147483647])

In [68]:
start = - (2**32) // 2 

end = (2**32) // 2 - 1

start, end

(-2147483648, 2147483647)

In [81]:
np.array([1,5,8,0, 2147483648], dtype=np.uint32)

array([         1,          5,          8,          0, 2147483648],
      dtype=uint32)

In [79]:
start = 0
end = 2**32

start, end

(0, 4294967296)

In [83]:
np.array([1,5,8,0, 2147483648], dtype=np.int64)

array([         1,          5,          8,          0, 2147483648],
      dtype=int64)

In [85]:
np.array([1,5,2,0, 2147483648], dtype=np.uint64)

array([         1,          5,          2,          0, 2147483648],
      dtype=uint64)

In [86]:
np.array([1.1,5.1,8,0, 2147483648], dtype=np.float16)

array([1.1, 5.1, 8. , 0. , inf], dtype=float16)

In [88]:
np.array([1.1,5.1,-8,0, 2147483648], dtype=np.float32)

array([ 1.1000000e+00,  5.0999999e+00, -8.0000000e+00,  0.0000000e+00,
        2.1474836e+09], dtype=float32)

In [89]:
np.array([1.1,5.1,-8,0, 2147483648], dtype=np.float64)

array([ 1.10000000e+00,  5.10000000e+00, -8.00000000e+00,  0.00000000e+00,
        2.14748365e+09])

In [91]:
np.array([1.1,5.1j], dtype=np.complex64)

array([1.1+0.j , 0. +5.1j], dtype=complex64)

In [92]:
np.array([1.1,5.1j], dtype=np.complex128)

array([1.1+0.j , 0. +5.1j])

In [94]:
np.array([True, True, False], dtype=np.bool_)

array([ True,  True, False])

In [97]:
np.array([list, tuple, dict, Exception, object], dtype=np.object_)

array([<class 'list'>, <class 'tuple'>, <class 'dict'>,
       <class 'Exception'>, <class 'object'>], dtype=object)

In [100]:
np.array(['abc', 'defp'], dtype=np.string_)

array([b'abc', b'defp'], dtype='|S4')

In [103]:
np.array(['₹'], dtype=np.unicode_)

array(['₹'], dtype='<U1')