In [1]:
import numpy as np

In [2]:
l1 = [1,2,3]
l2 = [7.8, 9.3, 5.5]


arr1 = np.array(l1)
arr2 = np.array(l2)

In [3]:
arr1

array([1, 2, 3])

In [4]:
arr2

array([7.8, 9.3, 5.5])

In [5]:
arr1 + arr2

array([ 8.8, 11.3,  8.5])

In [7]:
arr2 - arr1

array([6.8, 7.3, 2.5])

In [8]:
arr1 * arr2

array([ 7.8, 18.6, 16.5])

In [9]:
arr1 / arr2

array([0.12820513, 0.21505376, 0.54545455])

In [10]:
arr1 // arr2

array([0., 0., 0.])

In [20]:
l3 = [1,2,3]
l4 = [7.8, 9.3]


arr3 = np.array(l3)
arr4 = np.array(l4)

In [21]:
arr3

array([1, 2, 3])

In [22]:
arr4

array([7.8, 9.3])

In [23]:
arr3 + arr4

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [24]:
arr3 * arr4

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [25]:
l5 = [[1,2,3],[4,5,6]]
l6 = [[8.7, 5, 3.2], [9.7, 5.5,6]]

arr5 = np.array(l5)
arr6 = np.array(l6)

In [26]:
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr6

array([[8.7, 5. , 3.2],
       [9.7, 5.5, 6. ]])

In [28]:
arr5 + arr5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [29]:
arr5 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [30]:
arr5 + arr6

array([[ 9.7,  7. ,  6.2],
       [13.7, 10.5, 12. ]])

In [31]:
arr5 - arr6

array([[-7.7, -3. , -0.2],
       [-5.7, -0.5,  0. ]])

In [32]:
arr5 * arr6

array([[ 8.7, 10. ,  9.6],
       [38.8, 27.5, 36. ]])

In [33]:
arr5 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [34]:
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
1 / arr5

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [36]:
arr5 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [39]:
arr5 > 3

array([[False, False, False],
       [ True,  True,  True]])

In [61]:
l8 = [1, 2, 3]

l9 = [[1,2,3], [4,5,6]]

arr8 = np.array(l8)
arr9 = np.array(l9)

In [62]:
arr8

array([1, 2, 3])

In [63]:
arr9

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr9 - arr8

array([[0, 0, 0],
       [3, 3, 3]])

In [ ]:
[1,2,3] - [7, 8, 9]
[4,5,6] - [7, 8, 9]