In [1]:
import numpy as np

In [2]:
list1 = [1,5,8,56]

In [3]:
arr1 = np.array(list1)
arr1

array([ 1,  5,  8, 56])

In [4]:
arr1[0] = 10

In [5]:
arr1

array([10,  5,  8, 56])

In [6]:
arr1[:2]

array([10,  5])

In [7]:
arr1[:2] = 55

In [8]:
arr1

array([55, 55,  8, 56])

In [9]:
arr2 = arr1.copy()
arr2

array([55, 55,  8, 56])

In [10]:
arr2[:2] = 102
arr2

array([102, 102,   8,  56])

In [11]:
arr1

array([55, 55,  8, 56])

In [12]:
arr2 = arr1

arr2

array([55, 55,  8, 56])

In [13]:
arr2[:2] = 102

In [14]:
arr2

array([102, 102,   8,  56])

In [15]:
arr1

array([102, 102,   8,  56])