In [1]:
import numpy as np

In [2]:
list2D = [[6, 7, 8],
          [55, 66, 89],
          [69, 45, 32]]

In [4]:
arr2d = np.array(list2D)
arr2d

array([[ 6,  7,  8],
       [55, 66, 89],
       [69, 45, 32]])

In [5]:
arr2d[0]

array([6, 7, 8])

In [6]:
arr2d[2]

array([69, 45, 32])

In [7]:
arr2d[1] = 52

In [8]:
arr2d

array([[ 6,  7,  8],
       [52, 52, 52],
       [69, 45, 32]])

In [9]:
arr2d[0] = 84

arr2d

array([[84, 84, 84],
       [52, 52, 52],
       [69, 45, 32]])

In [10]:
list2D = [[6, 7, 8],
          [55, 66, 89],
          [69, 45, 32]]

arr2d = np.array(list2D)
arr2d

array([[ 6,  7,  8],
       [55, 66, 89],
       [69, 45, 32]])

In [16]:
arr2d[0][1] = 122

In [17]:
arr2d

array([[  6, 122,   8],
       [ 55,  66,  89],
       [ 69,  45,  32]])

In [18]:
arr2d[0,1]

122

In [20]:
arr2d[0][1:]

array([122,   8])

In [21]:
arr2d[0,1:]

array([122,   8])

In [41]:
arr2d[0][1:]

array([122,   8])

In [42]:
arr2d[1][1:]

array([66, 89])

In [31]:
arr2d[:2, 1:]

array([[122,   8],
       [ 66,  89]])

In [43]:
arr2d

array([[  6, 122,   8],
       [ 55,  66,  89],
       [ 69,  45,  32]])

In [47]:
arr2d[:,0]

array([ 6, 55, 69])

In [46]:
arr2d[:,:1]

array([[ 6],
       [55],
       [69]])

In [52]:
arr2d

array([[  6, 122,   8],
       [ 55,  66,  89],
       [ 69,  45,  32]])

In [53]:
arr2d[:,0]

array([ 6, 55, 69])

In [54]:
arr2d[:,0]=0

In [55]:
arr2d

array([[  0, 122,   8],
       [  0,  66,  89],
       [  0,  45,  32]])

In [57]:
arr2d.shape

(3, 3)

In [ ]:
# 3D -> indexing -> output -> 2D

# 3D -> slicing -> output -> 3D

# Same goes for other dimentions

In [62]:
arr2d

array([[  0, 122,   8],
       [  0,  66,  89],
       [  0,  45,  32]])

In [63]:
arr2d[0]

array([  0, 122,   8])

In [64]:
arr2d[1:]

array([[ 0, 66, 89],
       [ 0, 45, 32]])