In [1]:
import numpy as np

In [2]:
arr = np.zeros((8, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [4]:
arr[2]

array([2., 2., 2., 2.])

In [5]:
arr[3]

array([3., 3., 3., 3.])

In [6]:
arr[4]

array([4., 4., 4., 4.])

In [7]:
arr[2:5]

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [8]:
arr[[2, 3, 4]]

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [9]:
arr[[7, 4, 1]]

array([[7., 7., 7., 7.],
       [4., 4., 4., 4.],
       [1., 1., 1., 1.]])

In [10]:
arr[[-1, -2, -3]]

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [5., 5., 5., 5.]])

In [11]:
arr[-1:-4:-1]

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [5., 5., 5., 5.]])

In [12]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [13]:
arr = np.arange(32).reshape(8, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [14]:
arr[2, 2]

10

In [15]:
arr[5, 0]

20

In [16]:
arr[7, 2]

30

In [17]:
arr[[2, 5, 7], [2, 0, 2]]

array([10, 20, 30])

In [18]:
(2, 2),
(5, 0),
(7, 2)

(7, 2)

In [22]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [23]:
arr[[2, 2, 5, 5], [0, 2, 0, 2]]

array([ 8, 10, 20, 22])

In [26]:
arr[[2, 5]][:, [0, 2]]

array([[ 8, 10],
       [20, 22]])

In [27]:
new_arr = arr[[2, 2, 5, 5], [0, 2, 0, 2]]
new_arr

array([ 8, 10, 20, 22])

In [28]:
new_arr[:] = 0

In [29]:
new_arr

array([0, 0, 0, 0])

In [30]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [32]:
arr[[2, 2, 5, 5], [0, 2, 0, 2]] = 101

In [33]:
arr

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [101,   9, 101,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [101,  21, 101,  23],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31]])